/**
 * Download the three locked typefaces and bundle them.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * PLAN §5 locks the typography: Rajdhani for UI, names and numbers; Barlow for body;
 * JetBrains Mono for usernames and technical values. The mockup pulled them from Google Fonts
 * over the network, which a packaged desktop app should not do — it makes first paint depend on
 * connectivity, and the renderer's CSP otherwise has to allow remote origins for no other
 * reason.
 *
 * So the woff2 files are fetched once, written into src/renderer/fonts/, and served locally
 * with a generated @font-face block. Only the weights the design actually uses are pulled.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const outDir = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "renderer", "fonts");
mkdirSync(outDir, { recursive: true });

/** Weights taken straight from the locked spec — nothing speculative. */
const FAMILIES = [
  { family: "Rajdhani", weights: [500, 600, 700] },
  { family: "Barlow", weights: [400, 500, 600] },
  { family: "JetBrains Mono", weights: [400, 500] },
];

// A modern browser UA is required or Google serves legacy ttf instead of woff2.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const faces = [];
let failures = 0;

for (const { family, weights } of FAMILIES) {
  const spec = `${family.replace(/ /g, "+")}:wght@${weights.join(";")}`;
  const cssUrl = `https://fonts.googleapis.com/css2?family=${spec}&display=swap`;

  let css;
  try {
    const res = await fetch(cssUrl, { headers: { "User-Agent": UA }, signal: AbortSignal.timeout(20_000) });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    css = await res.text();
  } catch (err) {
    console.log(`  FAIL ${family}: ${err.message}`);
    failures++;
    continue;
  }

  // Google returns one @font-face block per unicode-range subset. The latin subset is all this
  // app needs — Riot IDs are latin — so taking the last block per weight keeps the bundle small.
  const blocks = css.split("@font-face").slice(1);
  const byWeight = new Map();

  for (const block of blocks) {
    const weight = Number(block.match(/font-weight:\s*(\d+)/)?.[1]);
    const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1] ?? "";
    if (!weight || !url) continue;
    // Prefer the plain latin subset over latin-ext and the rest.
    const isLatin = range.includes("U+0000-00FF") || range.includes("U+0-FF");
    if (isLatin || !byWeight.has(weight)) byWeight.set(weight, url);
  }

  for (const [weight, url] of byWeight) {
    const slug = `${family.toLowerCase().replace(/ /g, "-")}-${weight}.woff2`;
    try {
      const res = await fetch(url, { headers: { "User-Agent": UA }, signal: AbortSignal.timeout(20_000) });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const bytes = Buffer.from(await res.arrayBuffer());
      writeFileSync(join(outDir, slug), bytes);
      faces.push({ family, weight, slug, bytes: bytes.length });
      console.log(`  ${family.padEnd(16)} ${weight}  ${String(bytes.length).padStart(6)}B  -> ${slug}`);
    } catch (err) {
      console.log(`  FAIL ${family} ${weight}: ${err.message}`);
      failures++;
    }
  }
}

const cssOut = [
  "/*",
  " * Generated by scripts/fetch-fonts.mjs — do not edit by hand.",
  " *",
  " * The locked typefaces, bundled rather than fetched at runtime so the app renders correctly",
  " * offline and the renderer's CSP can forbid remote origins outright.",
  " */",
  "",
  ...faces.map((f) =>
    [
      "@font-face{",
      `  font-family:"${f.family}";`,
      `  font-style:normal;`,
      `  font-weight:${f.weight};`,
      `  font-display:swap;`,
      `  src:url("./fonts/${f.slug}") format("woff2");`,
      "}",
    ].join("\n")
  ),
  "",
].join("\n");

writeFileSync(join(outDir, "..", "fonts.css"), cssOut, "utf8");

console.log(`\n${faces.length} face(s) bundled, ${failures} failure(s) -> ${outDir}`);
process.exit(failures > 0 && faces.length === 0 ? 1 : 0);
